FROM node:24-alpine3.21 AS base

ARG TURBO_TOKEN

ARG TURBO_TEAM

# Stage 1 - Builder
FROM base AS builder

RUN apk update

WORKDIR /app

COPY /out/json .

RUN npm install

COPY /out/full .

RUN npm run db:generate

ENV TURBO_TOKEN=$TURBO_TOKEN
ENV TURBO_TEAM=$TURBO_TEAM

RUN npm run build

# Stage 2 - Prod Installer
FROM base AS prod-installer

WORKDIR /app

COPY /out/json .

RUN rm -r packages/eslint-config
RUN rm -r packages/nodemon-config
RUN rm -r packages/typescript-config

ENV NODE_ENV="production"

RUN npm install --ignore-scripts

# Stage 3 - Runner
FROM base AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 app-group
RUN adduser --system --uid 1001 app-user
USER app-user

COPY --from=prod-installer --chown=app-user:app-group /app .
COPY --from=builder --chown=app-user:app-group /app/apps/socket/dist /app/apps/socket/dist
COPY --from=builder --chown=app-user:app-group /app/packages/db/dist /app/packages/db/dist
COPY --from=builder --chown=app-user:app-group /app/packages/db/generated /app/packages/db/generated
COPY --from=builder --chown=app-user:app-group /app/packages/env/dist /app/packages/env/dist
COPY --from=builder --chown=app-user:app-group /app/packages/jwt/dist /app/packages/jwt/dist
COPY --from=builder --chown=app-user:app-group /app/packages/redis/dist /app/packages/redis/dist
COPY --from=builder --chown=app-user:app-group /app/packages/validation/dist /app/packages/validation/dist

WORKDIR /app/apps/socket

CMD [ "npm", "run", "start" ]
