name: Build and Deploy Proxy Server
on:
    workflow_run: 
        workflows: ["Lint and Build Pipeline"]
        types: [completed]

jobs:
    ignore-check:
        runs-on: ubuntu-latest
        outputs:
            code: ${{ steps.check.outputs.code }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: RUn the script
              id: check
              run: |
                chmod 700 ./scripts/ignore-build-check.sh

                ./scripts/ignore-build-check.sh proxy-server

    build-and-deploy-proxy-server:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: 
            ignore-check
        if: ${{ needs.ignore-check.outputs.code != 0 }}

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Prune the codebase for Deploy Server
              run: npx turbo prune proxy-server --docker

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push the Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./docker/Dockerfile.proxy-server
                build-args: |
                    TURBO_TOKEN=${{ secrets.TURBO_TOKEN}}
                    TURBO_TEAM=${{ vars.TURBO_TEAM }}
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/uplora-proxy-server:${{ github.sha }}

            - name: Start the Docker container
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/uplora-proxy-server:${{ github.sha }}

                      docker stop uplora-proxy-server || true
                      docker rm uplora-proxy-server || true
                      
                      docker run -d \
                        --name uplora-proxy-server \
                        -p ${{ secrets.REQ_HANDLER_PORT }}:${{ secrets.REQ_HANDLER_PORT }} \
                        -e REQ_HANDLER_PORT=${{ secrets.REQ_HANDLER_PORT }} \
                        -e PROXY_TARGET_URL=${{ secrets.PROXY_TARGET_URL }} \
                        -e ABS_SAS_TOKEN="${{ secrets.ABS_SAS_TOKEN }}" \
                        --restart unless-stopped \
                        ${{ secrets.DOCKERHUB_USERNAME }}/uplora-proxy-server:${{ github.sha }}
