name: Build and Deploy Upload Server
on:
    workflow_run: 
        workflows: ["Lint and Build Pipeline"]
        types: [completed]

jobs:
    ignore-check:
        runs-on: ubuntu-latest
        outputs:
            code: ${{ steps.check.outputs.code }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Run the script
              id: check
              run: |
                chmod 700 ./scripts/ignore-build-check.sh

                ./scripts/ignore-build-check.sh upload-server

    build-and-deploy-upload-server:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: 
          ignore-check
        if: ${{ needs.ignore-check.outputs.code !=0 }}
        
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Prune the codebase for Upload Server
              run: npx turbo prune upload-server --docker

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push the Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./docker/Dockerfile.upload-server
                build-args: |
                    TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
                    TURBO_TEAM=${{ vars.TURBO_TEAM }}
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/uplora-upload-server:${{ github.sha }}

            - name: Start the Docker container
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/uplora-upload-server:${{ github.sha }}

                      docker stop uplora-upload-server || true
                      docker rm uplora-upload-server || true

                      docker run -d \
                        --name uplora-upload-server \
                        -p ${{ secrets.UPLOAD_PORT }}:${{ secrets.UPLOAD_PORT }} \
                        -e UPLOAD_PORT=${{ secrets.UPLOAD_PORT }} \
                        -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                        -e ABS_CONNECTION_URL="${{ secrets.ABS_CONNECTION_URL }}" \
                        -e ABS_CONTAINER_NAME=${{ secrets.ABS_CONTAINER_NAME }} \
                        -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                        -e REDIS_URL=${{ secrets.REDIS_URL }} \
                        --restart unless-stopped \
                        ${{ secrets.DOCKERHUB_USERNAME }}/uplora-upload-server:${{ github.sha }}
