name: Lint and Build Pipeline

on: 
    push: 
        branches: 
            - main

jobs:
    lint-and-build-test:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN}}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Generate client
              run: npm run db:generate

            - name: Lint the code
              run: npm run lint

            - name: Build the code
              run: npm run build