name: Build and Deploy Pipeline

on: 
    push: 
        branches: 
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Lint the code
              run: npm run lint

            - name: Build the code
              run: npm run build

            # - name: Deploy the code
            #   run: npm run deploy